*** Reading local file: /opt/airflow/logs/increment/0_1/2021-08-30T04:03:05.174490+00:00/1.log
[2021-08-30 04:03:18,444] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: increment.0_1 2021-08-30T04:03:05.174490+00:00 [queued]>
[2021-08-30 04:03:18,460] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: increment.0_1 2021-08-30T04:03:05.174490+00:00 [queued]>
[2021-08-30 04:03:18,460] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-08-30 04:03:18,460] {taskinstance.py:1095} INFO - Starting attempt 1 of 1
[2021-08-30 04:03:18,460] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-08-30 04:03:18,468] {taskinstance.py:1114} INFO - Executing <Task(_PythonDecoratedOperator): 0_1> on 2021-08-30T04:03:05.174490+00:00
[2021-08-30 04:03:18,470] {standard_task_runner.py:52} INFO - Started process 13 to run task
[2021-08-30 04:03:18,473] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'increment', '0_1', '2021-08-30T04:03:05.174490+00:00', '--job-id', '3', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/bad.py', '--cfg-path', '/tmp/tmp66f03zae', '--error-file', '/tmp/tmp18h4wrnj']
[2021-08-30 04:03:18,474] {standard_task_runner.py:77} INFO - Job 3: Subtask 0_1
[2021-08-30 04:03:18,513] {logging_mixin.py:109} INFO - Running <TaskInstance: increment.0_1 2021-08-30T04:03:05.174490+00:00 [running]> on host increment01.45dd8e0ddbde45caa5eca448caabff72
[2021-08-30 04:03:18,579] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=increment
AIRFLOW_CTX_TASK_ID=0_1
AIRFLOW_CTX_EXECUTION_DATE=2021-08-30T04:03:05.174490+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-30T04:03:05.174490+00:00
[2021-08-30 04:03:18,580] {logging_mixin.py:109} INFO - command:
[2021-08-30 04:03:18,580] {logging_mixin.py:109} INFO - kubectl run vtqvwvg --rm -n freezebug --restart=Never -i --image=bash -- sleep 0.1
[2021-08-30 04:03:18,590] {sh.py:670} INFO - <Command "/bin/sh -c 'kubectl run vtqvwvg --rm -n freezebug --restart=Never -i --image=bash -- sleep 0.1'", pid 14>: process started
[2021-08-30 04:03:21,018] {logging_mixin.py:109} INFO - result:
[2021-08-30 04:03:21,019] {logging_mixin.py:109} INFO - pod "vtqvwvg" deleted
[2021-08-30 04:03:21,019] {logging_mixin.py:109} INFO - 
[2021-08-30 04:03:21,019] {python.py:151} INFO - Done. Returned value was: None
[2021-08-30 04:03:21,033] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=increment, task_id=0_1, execution_date=20210830T040305, start_date=20210830T040318, end_date=20210830T040321
[2021-08-30 04:03:21,091] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-08-30 04:03:21,121] {local_task_job.py:261} INFO - 1 downstream tasks scheduled from follow-on schedule check
